### PR TITLE
Refactored database to use mLabs instead of Parse.

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
I rebuilt how environment variables are handled so that we could have it work for any system (Windows, Mac, etc.).

The readme has also been updated, so you should be able to follow that during your testing.

Essentially:

```
npm install
npm run setup
npm start
```

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Hey @Blackbaud-SteveBrush, are the [Run Barkbaud on your server](https://github.com/blackbaud/barkbaud/blob/feature-database-refactoring/README.md#run-barkbaud-on-your-server) and [Installation Summary](https://github.com/blackbaud/barkbaud/blob/feature-database-refactoring/README.md#installation-summary) sections of the README.md basically the same?

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl: Essentially, yes. I suppose we could remove Installation Summary; I was emulating the original README's [walkthrough](https://github.com/blackbaud/barkbaud#install-dependencies-and-run-the-application), and "[Examples](https://github.com/blackbaud/barkbaud#osxlinux-example)".

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl Removed the Summary section.

**Comment by Blackbaud-BobbyEarl** [comment]
Apologies on the delay, looks great @Blackbaud-SteveBrush!

**Pull request merged**
